# Generated by Django 3.0.7 on 2020-10-19 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaggUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(default="", max_length=60, unique=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("is_validated", models.BooleanField(default=False)),
                ("password_log", models.CharField(default="", max_length=128)),
                ("biography", models.CharField(blank=True, max_length=150)),
                ("website", models.CharField(blank=True, max_length=100)),
                ("birthday", models.DateField(default=None, null=True)),
                ("gender", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="InvitationCode",
            fields=[
                (
                    "hexcode",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fb_user_id", models.CharField(max_length=128)),
                ("fb_access_token", models.CharField(max_length=256)),
                ("ig_user_id", models.CharField(max_length=128)),
                ("ig_access_token", models.CharField(max_length=256)),
                ("twitter_oauth_token", models.CharField(default="", max_length=64)),
                (
                    "twitter_oauth_token_secret",
                    models.CharField(default="", max_length=64),
                ),
                ("twitter_user_id", models.CharField(default="", max_length=64)),
                ("twitter_screen_name", models.CharField(default="", max_length=64)),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MomentMetadata",
            fields=[
                (
                    "moment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("caption", models.CharField(max_length=256)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("path_hash", models.CharField(max_length=256)),
                ("moment_category", models.CharField(max_length=128)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "followed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tagguser",
            index=models.Index(fields=["id"], name="backend_tag_id_bd82f4_idx"),
        ),
        migrations.AddIndex(
            model_name="tagguser",
            index=models.Index(
                fields=["username"], name="backend_tag_usernam_86707b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tagguser",
            index=models.Index(fields=["email"], name="backend_tag_email_fb295f_idx"),
        ),
        migrations.AddIndex(
            model_name="momentmetadata",
            index=models.Index(
                fields=["moment_id"], name="backend_mom_moment__e4cd15_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("followed", "follower")},
        ),
    ]
