# Generated by Django 3.0.7 on 2020-10-20 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_auto_20201019_1856"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="snapchat_url",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="tiktok_url",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="follow",
            name="followed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
