# Generated by Django 3.0.7 on 2020-10-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_auto_20201020_0041"),
        ("backend", "0004_auto_20201020_1514"),
    ]

    operations = []
