# Generated by Django 3.0.7 on 2020-11-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_blockeduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="momentmetadata",
            name="resource_path",
            field=models.CharField(default="", max_length=256),
        ),
    ]
