# Generated by Django 3.0.7 on 2020-12-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_momentmetadata_resource_path"),
        ("backend", "0008_auto_20201130_1959"),
    ]

    operations = []
