# Generated by Django 3.0.7 on 2020-12-16 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_merge_20201209_0631"),
    ]

    operations = [
        migrations.CreateModel(
            name="MomentCategoryMetadata",
            fields=[
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("moments_category", models.CharField(max_length=256)),
            ],
        ),
    ]
