# Generated by Django 3.0.7 on 2020-12-30 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_momentcategorymetadata"),
        ("backend", "0010_auto_20201215_1905"),
    ]

    operations = []
