# Generated by Django 3.0.7 on 2020-12-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_change_follow_to_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagguser",
            name="university",
            field=models.CharField(default="Brown University", max_length=256),
        ),
        migrations.AddField(
            model_name="tagguser",
            name="university_class",
            field=models.IntegerField(default=2021),
        ),
    ]
