# Generated by Django 3.0.7 on 2020-12-30 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_auto_20201229_1557"),
        ("backend", "0013_auto_20201228_0530"),
    ]

    operations = []
