# Generated by Django 3.0.7 on 2020-12-30 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_merge_20201230_0517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_object",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.MomentComments",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("DFT", "Default"), ("FRD", "Friend"), ("CMT", "Comment")],
                default="DFT",
                max_length=4,
            ),
        ),
    ]
