# Generated by Django 3.0.7 on 2020-12-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0015_auto_20201230_0825"),
        ("backend", "0011_merge_20201230_0026"),
    ]

    operations = []
