# Generated by Django 3.0.7 on 2021-01-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0017_auto_20201231_0112"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MomentMetadata",
            new_name="Moment",
        ),
        migrations.RenameModel(
            old_name="MomentCategoryMetadata",
            new_name="MomentCategory",
        ),
        migrations.RemoveIndex(
            model_name="moment",
            name="backend_mom_moment__e4cd15_idx",
        ),
        migrations.RemoveIndex(
            model_name="moment",
            name="backend_mom_user_id_d32c02_idx",
        ),
        migrations.RenameField(
            model_name="moment",
            old_name="date_time",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="momentcomments",
            old_name="date_time",
            new_name="date_created",
        ),
        migrations.AddIndex(
            model_name="moment",
            index=models.Index(
                fields=["moment_id"], name="backend_mom_moment__b9053b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moment",
            index=models.Index(
                fields=["user_id"], name="backend_mom_user_id_da9eb3_idx"
            ),
        ),
    ]
