# Generated by Django 3.0.7 on 2021-01-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_merge_20201222_1746"),
        ("backend", "0017_auto_20201231_0112"),
    ]

    operations = []
