# Generated by Django 3.0.7 on 2021-01-05 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0017_auto_20201231_0112"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "phone_number",
                    models.CharField(default="", max_length=12, unique=True),
                ),
            ],
        ),
    ]
