# Generated by Django 3.0.7 on 2021-01-08 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0018_tagguser_profile_completion_stage"),
        ("backend", "0018_auto_20210107_1753"),
    ]

    operations = []
