# Generated by Django 3.0.7 on 2021-01-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0018_waitlistuser"),
        ("backend", "0019_merge_20210108_0059"),
    ]

    operations = []
