# Generated by Django 3.0.7 on 2021-01-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0018_merge_20210103_1852"),
        ("backend", "0020_merge_20210112_2000"),
    ]

    operations = []
