# Generated by Django 3.0.7 on 2021-01-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0019_auto_20210108_2318"),
        ("backend", "0020_merge_20210112_2000"),
    ]

    operations = []
