# Generated by Django 3.0.7 on 2021-01-16 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0021_merge_20210114_0304"),
        ("backend", "0021_merge_20210115_0009"),
    ]

    operations = []
