# Generated by Django 3.0.7 on 2021-01-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0022_merge_20210116_0150"),
        ("backend", "0011_merge_20201222_1746"),
    ]

    operations = []
