# Generated by Django 3.0.7 on 2021-01-22 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0022_merge_20210116_0150"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friends",
            name="status",
            field=models.CharField(
                choices=[("requested", "Requested"), ("friends", "Friends")],
                default="requested",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="momentcategory",
            name="moments_category",
            field=models.CharField(max_length=1024),
        ),
        migrations.CreateModel(
            name="CommentThreads",
            fields=[
                (
                    "comment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.CharField(max_length=256)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "commenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.MomentComments",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="commentthreads",
            index=models.Index(
                fields=["parent_comment"], name="backend_com_parent__be358d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentthreads",
            index=models.Index(
                fields=["comment_id"], name="backend_com_comment_7f3350_idx"
            ),
        ),
    ]
