# Generated by Django 3.0.7 on 2021-01-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0021_merge_20210113_2022"),
        ("backend", "0023_merge_20210116_1851"),
    ]

    operations = []
