# Generated by Django 3.0.7 on 2021-01-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0023_auto_20210122_0240"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moment",
            old_name="path_hash",
            new_name="moment_url",
        ),
        migrations.AddField(
            model_name="moment",
            name="thumbnail_url",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
