# Generated by Django 3.0.7 on 2021-02-08 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0025_auto_20210131_0748"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversityBadge",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("university", models.CharField(max_length=2048)),
                ("category", models.CharField(max_length=1048)),
            ],
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("DFT", "Default"),
                    ("FRD_REQ", "Friend Request"),
                    ("FRD_ACPT", "Friend Acceptance"),
                    ("CMT", "Comment"),
                    ("LKT", "Link Taggs"),
                    ("MOM_3+", "Moment 3P"),
                    ("MOM_FRIEND", "Moment Friend"),
                ],
                default="DFT",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge",
                        to="backend.UniversityBadge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="universitybadge",
            index=models.Index(fields=["id"], name="backend_uni_id_10ad9f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="universitybadge",
            unique_together={("name", "university")},
        ),
        migrations.AddIndex(
            model_name="userbadge",
            index=models.Index(fields=["user"], name="backend_use_user_id_bc174e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={("user", "badge")},
        ),
    ]
