# Generated by Django 3.0.7 on 2021-02-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0026_auto_20210208_0134"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagguser",
            name="suggested_people_linked",
            field=models.IntegerField(choices=[(0, "False"), (1, "True")], default=0),
        ),
    ]
