# Generated by Django 3.0.7 on 2021-02-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0027_tagguser_suggested_people_linked"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagguser",
            name="sp_swipe_tutorial",
            field=models.IntegerField(choices=[(0, "False"), (1, "True")], default=0),
        ),
    ]
