# Generated by Django 3.0.7 on 2021-02-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0028_tagguser_sp_swipe_tutorial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tagguser",
            name="sp_swipe_tutorial",
        ),
        migrations.AlterField(
            model_name="tagguser",
            name="suggested_people_linked",
            field=models.IntegerField(
                choices=[
                    (0, "Initial"),
                    (1, "Picture Uploaded"),
                    (2, "Final Tutorial"),
                ],
                default=0,
            ),
        ),
    ]
