# Generated by Django 3.0.7 on 2021-03-18 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0031_search_revamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteFriends",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invitee_phone_number",
                    models.CharField(default="", max_length=12, unique=True),
                ),
                ("invitee_first_name", models.CharField(max_length=50)),
                ("invitee_last_name", models.CharField(max_length=50)),
                ("inviter_fullname", models.CharField(default="", max_length=110)),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="invitefriends",
            index=models.Index(
                fields=["invitee_phone_number"], name="backend_inv_invitee_668f18_idx"
            ),
        ),
    ]
