# Generated by Django 3.0.7 on 2021-03-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0033_invited_for_invited_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagguser",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
