# Generated by Django 3.0.7 on 2021-03-27 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0034_waitlist_invited"),
        ("backend", "0034_private_accounts"),
    ]

    operations = []
