# Generated by Django 3.0.7 on 2021-04-02 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0037_auto_20210327_0406"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("chat_token", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(fields=["user"], name="backend_cha_user_id_230ef7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together={("user", "chat_token")},
        ),
    ]
