# Generated by Django 3.0.7 on 2021-04-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0038_chat_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_token",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("DFT", "Default"),
                    ("FRD_REQ", "Friend Request"),
                    ("FRD_ACPT", "Friend Acceptance"),
                    ("CMT", "Comment"),
                    ("LKT", "Link Taggs"),
                    ("MOM_3+", "Moment 3P"),
                    ("MOM_FRIEND", "Moment Friend"),
                    ("INVT_ONBRD", "Invitee Onboarded"),
                ],
                default="DFT",
                max_length=10,
            ),
        ),
    ]
