# Generated by Django 3.0.7 on 2021-04-16 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0039_stale_changes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeopleRecommender",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("friend_feature", models.FloatField()),
                ("university_feature", models.FloatField()),
                ("badge_feature", models.FloatField()),
                ("class_year_feature", models.FloatField()),
                ("interested_feature", models.FloatField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("dirty", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendatation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="peoplerecommender",
            index=models.Index(fields=["id"], name="backend_peo_id_14e65b_idx"),
        ),
        migrations.AddIndex(
            model_name="peoplerecommender",
            index=models.Index(
                fields=["recipient"], name="backend_peo_recipie_d40695_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="peoplerecommender",
            unique_together={("recipient", "recommendation")},
        ),
    ]
