# Generated by Django 3.0.7 on 2021-04-19 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0040_people_recommender"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileVisits",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitors", models.CharField(blank=True, max_length=1024)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="profilevisits",
            index=models.Index(fields=["user"], name="backend_pro_user_id_da41d1_idx"),
        ),
    ]
