# Generated by Django 3.0.7 on 2021-04-01 23:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0041_profile_visits"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPushNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.CharField(max_length=256)),
            ],
        )
    ]
