# Generated by Django 3.0.7 on 2021-05-13 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0043_increase_comment_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitefriends",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("DFT", "Default"),
                    ("FRD_REQ", "Friend Request"),
                    ("FRD_ACPT", "Friend Acceptance"),
                    ("CMT", "Comment"),
                    ("LKT", "Link Taggs"),
                    ("MOM_3+", "Moment 3P"),
                    ("MOM_FRIEND", "Moment Friend"),
                    ("INVT_ONBRD", "Invitee Onboarded"),
                    ("SYSTEM_MSG", "System Msg"),
                ],
                default="DFT",
                max_length=10,
            ),
        ),
    ]
