# Generated by Django 3.0.7 on 2021-05-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0044_invite_friends_date"),
        ("backend", "0045_auto_20210507_2022"),
    ]

    operations = []
