# Generated by Django 3.0.7 on 2021-05-17 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0047_auto_20210514_1842"),
    ]

    operations = [
        migrations.CreateModel(
            name="MomentTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("x", models.IntegerField(blank=True)),
                ("y", models.IntegerField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MomentTagList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.Moment"
                    ),
                ),
                (
                    "moment_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.MomentTag",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="momenttag",
            index=models.Index(fields=["id"], name="backend_mom_id_89d8b6_idx"),
        ),
    ]
