# Generated by Django 3.0.7 on 2021-05-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0049_notification_type_moment_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="momenttag",
            name="z",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="momenttag",
            name="x",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="momenttag",
            name="y",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
