# Generated by Django 3.0.7 on 2021-06-07 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_z_for_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggUserMeta',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='taggusermeta', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_private', models.BooleanField(default=False)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('waitlist_invited', models.BooleanField(default=False)),
                ('profile_completion_stage', models.IntegerField(choices=[(1, 'Stage 1'), (2, 'Stage 2'), (3, 'Stage 3'), (4, 'Complete')], default=1)),
                ('suggested_people_linked', models.IntegerField(choices=[(0, 'Initial'), (1, 'Picture Uploaded'), (2, 'Final Tutorial')], default=0)),
                ('last_seen_notifications', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DFT', 'Default'), ('FRD_REQ', 'Friend Request'), ('FRD_ACPT', 'Friend Acceptance'), ('CMT', 'Comment'), ('LKT', 'Link Taggs'), ('MOM_3+', 'Moment 3P'), ('MOM_FRIEND', 'Moment Friend'), ('INVT_ONBRD', 'Invitee Onboarded'), ('MOM_TAG', 'Moment Tag'), ('SYSTEM_MSG', 'System Msg'), ('P_VIEW', 'Profile View')], default='DFT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='taggusermeta',
            index=models.Index(fields=['user'], name='backend_tag_user_id_4f87d0_idx'),
        ),
    ]
