# Generated by Django 3.0.7 on 2021-06-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_auto_20210607_1923'),
        ('backend', '0051_ig_token_date'),
    ]

    operations = [
    ]
