# Generated by Django 3.0.7 on 2021-07-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0053_moment_tag_int_to_float"),
    ]

    operations = [
        migrations.AddField(
            model_name="moment",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
