# Generated by Django 3.0.7 on 2021-07-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_moment_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
