# Generated by Django 3.0.7 on 2021-09-02 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_share_count_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentViewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentviewrecord', to='backend.Moment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='momentviewrecord',
            index=models.Index(fields=['user'], name='backend_mom_user_id_2f3798_idx'),
        ),
        migrations.AddIndex(
            model_name='momentviewrecord',
            index=models.Index(fields=['moment'], name='backend_mom_moment__877f92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='momentviewrecord',
            unique_together={('user', 'moment')},
        ),
    ]
