# Generated by Django 3.0.7 on 2021-09-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_merge_20210116_1852'),
        ('backend', '0056_moment_view_record'),
    ]

    operations = [
    ]
