# Generated by Django 3.0.7 on 2021-10-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_moment_view_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagguser',
            name='is_onboarded',
        ),
        migrations.RemoveField(
            model_name='tagguser',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='tagguser',
            name='profile_completion_stage',
        ),
        migrations.RemoveField(
            model_name='tagguser',
            name='suggested_people_linked',
        ),
        migrations.RemoveField(
            model_name='tagguser',
            name='waitlist_invited',
        ),
    ]
