# Generated by Django 3.0.7 on 2021-10-20 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_remove_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('VIDEO_LINK', 'Video Link'), ('APPLICATION_LINK', 'Application Link'), ('GENERIC_LINK', 'Generic Link'), ('RECENT_MOMENT', 'Recent Moment')], max_length=64)),
                ('page', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationLinkWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Widget')),
                ('link_type', models.CharField(choices=[('SPOTIFY', 'Spotify'), ('SOUNDCLOUD', 'Soundcloud'), ('APPLE_MUSIC', 'Apple Music'), ('APPLE_PODCAST', 'Apple Podcast'), ('POSHMARK', 'Poshmark'), ('DEPOP', 'Depop'), ('ETSY', 'Etsy'), ('SHOPIFY', 'Shopify'), ('AMAZON', 'Amazon')], max_length=32)),
                ('url', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=32)),
                ('background_color', models.CharField(max_length=16)),
            ],
            bases=('backend.widget',),
        ),
        migrations.CreateModel(
            name='GenericLinkWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Widget')),
                ('url', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=32)),
                ('border_color', models.CharField(max_length=16)),
                ('thumbnail_url', models.CharField(max_length=512)),
            ],
            bases=('backend.widget',),
        ),
        migrations.CreateModel(
            name='RecentMomentWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Widget')),
                ('some_data', models.CharField(max_length=5)),
            ],
            bases=('backend.widget',),
        ),
        migrations.CreateModel(
            name='VideoLinkWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Widget')),
                ('link_type', models.CharField(choices=[('YOUTUBE', 'Youtube'), ('TIKTOK', 'Tiktok'), ('TWITCH', 'Twitch'), ('VIMEO', 'Vimeo')], max_length=32)),
                ('url', models.CharField(max_length=512)),
                ('border_color', models.CharField(max_length=16)),
                ('thumbnail_url', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=32)),
            ],
            bases=('backend.widget',),
        ),
    ]
