# Generated by Django 3.0.7 on 2021-10-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_revamp_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagguser',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
