# Generated by Django 3.0.7 on 2021-11-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_invitationcode_creation_date'),
        ('backend', '0061_add_instagram_handle'),
    ]

    operations = [
    ]
