# Generated by Django 3.0.7 on 2021-11-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_merge_20211102_0106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitefriends',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='invitefriends',
            name='invite_code',
        ),
        migrations.DeleteModel(
            name='InvitationCode',
        ),
    ]
