# Generated by Django 3.0.7 on 2021-11-04 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_remove_invitation_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterests',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('interests', models.CharField(max_length=1024)),
            ],
        ),
    ]
