# Generated by Django 3.0.7 on 2021-11-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_user_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPUser',
            fields=[
                ('phone_number', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
