# Generated by Django 3.0.7 on 2021-11-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_vip_users'),
        ('backend', '0063_longer_url_length'),
    ]

    operations = [
    ]
