# Generated by Django 3.0.7 on 2021-11-08 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0066_merge_20211107_2209"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("ONE", "One"),
                            ("TWO", "Two"),
                            ("THREE", "Three"),
                            ("FOUR", "Four"),
                            ("FIVE", "Five"),
                        ],
                        max_length=64,
                    ),
                ),
                ("primary_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("secondary_color", models.CharField(default="#698DD3", max_length=7)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
            ],
        ),
    ]
