# Generated by Django 3.0.7 on 2021-11-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_skin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MomentViewRecord',
        ),
    ]
