# Generated by Django 3.0.7 on 2021-11-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_moment_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='bio_color_end',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='skin',
            name='bio_color_start',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='skin',
            name='bio_text_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
