# Generated by Django 3.0.7 on 2021-11-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0070_add_bio_colors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationlinkwidget",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="genericlinkwidget",
            name="border_color",
        ),
        migrations.RemoveField(
            model_name="videolinkwidget",
            name="border_color",
        ),
        migrations.AddField(
            model_name="applicationlinkwidget",
            name="background_color_end",
            field=models.CharField(null=True, max_length=7),
        ),
        migrations.AddField(
            model_name="applicationlinkwidget",
            name="background_color_start",
            field=models.CharField(null=True, max_length=7),
        ),
        migrations.AddField(
            model_name="genericlinkwidget",
            name="border_color_end",
            field=models.CharField(null=True, max_length=7),
        ),
        migrations.AddField(
            model_name="genericlinkwidget",
            name="border_color_start",
            field=models.CharField(null=True, max_length=7),
        ),
        migrations.AddField(
            model_name="videolinkwidget",
            name="border_color_end",
            field=models.CharField(null=True, max_length=7),
        ),
        migrations.AddField(
            model_name="videolinkwidget",
            name="border_color_start",
            field=models.CharField(null=True, max_length=7),
        ),
    ]
