# Generated by Django 3.0.7 on 2021-11-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_add_bio_colors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='momentengagement',
            unique_together={('user', 'moment')},
        ),
    ]
