# Generated by Django 3.0.7 on 2021-11-19 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_unique_engagements'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Widget')),
                ('social_type', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instrgam'), ('TWITTER', 'Twitter'), ('SNAPCHAT', 'Snapchat'), ('TIKTOK', 'Tiktok')], max_length=32)),
                ('background_color_start', models.CharField(max_length=7, null=True)),
                ('background_color_end', models.CharField(max_length=7, null=True)),
            ],
            bases=('backend.widget',),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('VIDEO_LINK', 'Video Link'), ('APPLICATION_LINK', 'Application Link'), ('GENERIC_LINK', 'Generic Link'), ('RECENT_MOMENT', 'Recent Moment'), ('SOCIAL_MEDIA', 'Social Media')], max_length=64),
        ),
    ]
