# Generated by Django 3.0.7 on 2021-11-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_split_color_array_string'),
        ('backend', '0072_social_media_widgets'),
    ]

    operations = [
    ]
