# Generated by Django 3.0.7 on 2021-11-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_remove_field_from_recent_mom_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentmomentwidget',
            name='font_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
