# Generated by Django 3.0.7 on 2021-12-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_recentmomentwidget_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediawidget',
            name='username',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
