# Generated by Django 3.0.7 on 2021-12-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_alter_bio_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggusermeta',
            name='profile_completion_stage',
        ),
        migrations.AddField(
            model_name='taggusermeta',
            name='profile_tutorial_stage',
            field=models.IntegerField(choices=[(0, 'Stage 0'), (1, 'Stage 1'), (2, 'Complete')], default=0),
        ),
    ]
