# Generated by Django 3.0.7 on 2021-12-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_alter_bio_colors'),
        ('backend', '0057_merge_20210908_2203'),
    ]

    operations = [
    ]
