# Generated by Django 3.0.7 on 2021-12-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_merge_20211203_0431'),
        ('backend', '0078_auto_20211209_0141'),
    ]

    operations = [
    ]
