# Generated by Django 3.0.7 on 2021-12-27 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_auto_20211209_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasRated',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hasRated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='skin',
            name='primary_color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='skin',
            name='secondary_color',
            field=models.CharField(max_length=7),
        ),
    ]
