# Generated by Django 3.0.7 on 2021-12-23 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0079_auto_20211222_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCount',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
