# Generated by Django 3.0.7 on 2021-12-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0079_auto_20211224_0006"),
        ("backend", "0079_auto_20211227_2326"),
        ("backend", "0080_logincount"),
    ]

    operations = []
