# Generated by Django 3.0.7 on 2022-01-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0079_merge_20211214_0321'),
        ('backend', '0081_merge_20211230_0927'),
    ]

    operations = [
    ]
