# Generated by Django 3.0.7 on 2022-01-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_merge_20220103_2219'),
    ]

    operations = [ 
        migrations.AddField(
            model_name='applicationlinkwidget',
            name='thumbnail_url',
            field=models.CharField(default='https://tagg-prod.s3.us-east-2.amazonaws.com/misc/not+found.jpg', max_length=8192),
            preserve_default=False,
        ),
    ]
