# Generated by Django 3.0.7 on 2022-01-11 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0082_merge_20220103_2219"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameProfile",
            fields=[
                (
                    "tagg_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tagg_score", models.IntegerField(default=0)),
                (
                    "tier",
                    models.CharField(default="New kid on the Block", max_length=256),
                ),
            ],
        ),
    ]
