# Generated by Django 3.2.11 on 2022-01-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0083_applicationlinkwidget_thumbnail_url'),
        ('backend', '0083_gameprofile'),
    ]

    operations = [
    ]
