# Generated by Django 3.0.7 on 2022-01-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0083_gameprofile'),
        ('backend', '0083_applicationlinkwidget_thumbnail_url'),
    ]

    operations = [
    ]
