# Generated by Django 3.0.7 on 2022-01-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0084_merge_20220119_0137"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameprofile",
            name="rewards",
            field=models.CharField(default="[]", max_length=1024),
        ),
    ]
