# Generated by Django 3.0.7 on 2022-01-28 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0085_auto_20220127_1326"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="WidgetViews",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "visitor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "widget_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.Widget",
                    ),
                ),
            ],
        ),
    ]
