# Generated by Django 3.0.7 on 2022-01-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0086_auto_20220128_0103"),
    ]

    operations = [
        migrations.RenameField(
            model_name="widgetviews",
            old_name="visitor",
            new_name="viewer",
        ),
        migrations.RenameField(
            model_name="widgetviews",
            old_name="widget_id",
            new_name="widget",
        ),
    ]
