# Generated by Django 3.0.7 on 2022-01-31 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0087_auto_20220129_0126"),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialmediawidget",
            old_name="social_type",
            new_name="link_type",
        ),
        migrations.AlterField(
            model_name="widgetviews",
            name="widget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="widget",
                to="backend.Widget",
            ),
        ),
    ]
