# Generated by Django 3.2.11 on 2022-02-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_merge_20220120_1355'),
        ('backend', '0085_auto_20220127_1326'),
        ('backend', '0086_auto_20220127_2015'),
        ('backend', '0090_auto_20220131_1221'),
    ]

    operations = [
    ]
