# Generated by Django 3.0.7 on 2022-02-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0086_auto_20220127_2015'),
        ('backend', '0088_auto_20220131_2152'),
        ('backend', '0086_auto_20220126_2233'),
        ('backend', '0090_auto_20220131_1221'),
        ('backend', '0084_merge_20220120_1355'),
    ]

    operations = [
    ]
