# Generated by Django 3.2.11 on 2022-02-03 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0091_merge_20220203_0635'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='momentviews',
        #     name='profile_visitor',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_visitor', to=settings.AUTH_USER_MODEL),
        # ),
    ]
