# Generated by Django 3.2.11 on 2022-02-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0092_auto_20220203_0636'),
    ]

    operations = []
