# Generated by Django 3.2.11 on 2022-02-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0093_delete_momentcategorylist'),
    ]

    operations = []
