# Generated by Django 3.2.11 on 2022-02-03 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0095_alter_momentcategory_user_id'),
    ]

    operations = []
