# Generated by Django 3.2.11 on 2022-02-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0088_auto_20220131_2152'),
        ('backend', '0096_momentcategorylist_created_on'),
    ]

    operations = [
    ]
