# Generated by Django 3.2.11 on 2022-02-07 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0097_merge_20220207_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentcategory',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='momentcategory', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
