# Generated by Django 3.2.11 on 2022-02-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0098_auto_20220207_0612'),
    ]

    operations = []
