# Generated by Django 3.2.11 on 2022-02-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0099_momentcategorylist_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
