# Generated by Django 3.2.11 on 2022-02-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0100_auto_20220207_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentmomentwidget',
            name='indx',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
