# Generated by Django 3.0.7 on 2022-02-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0101_recentmomentwidget_indx'),
        ('backend', '0091_merge_20220202_2236'),
    ]

    operations = [
    ]
