# Generated by Django 3.2.11 on 2022-02-14 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0101_recentmomentwidget_indx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentCategoriesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_image', models.FileField(null=True, upload_to='cat_image')),
                ('cat_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
