# Generated by Django 3.2.11 on 2022-02-14 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0102_momentcategoriesimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentcategoriesimage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_image', to='backend.momentcategory'),
            preserve_default=False,
        ),
    ]
