# Generated by Django 3.0.7 on 2022-02-09 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0102_merge_20220209_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileviews',
            name='profile_visited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileviews',
            name='profile_visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='widgetviews',
            name='viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widget_viewer', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.CreateModel(
        #     name='MomentVisited',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        #         ('targetDate', models.DateField(auto_now_add=True)),
        #         ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Moment')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.AddIndex(
        #     model_name='momentvisited',
        #     index=models.Index(fields=['user_id', 'moment_id'], name='backend_mom_user_id_e7920d_idx'),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='momentvisited',
        #     unique_together={('user_id', 'moment_id')},
        # ),
    ]
