# Generated by Django 3.2.11 on 2022-02-14 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0103_momentcategoriesimage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentCategoryEditCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('lock', 'Lock'), ('unlock', 'Unlock')], default='lock', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='backend.momentcategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
