# Generated by Django 3.0.7 on 2022-02-09 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0104_tagguser_reward"),
    ]

    operations = [
        migrations.CreateModel(
            name="MomentScores",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=46),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MomentShares",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="momentviews",
            name="backend_mom_moment__cda92c_idx",
        ),
        migrations.RemoveField(
            model_name="momentviews",
            name="moment_visited",
        ),
        # migrations.RemoveField(
        #     model_name="momentviews",
        #     name="profile_visitor",
        # ),
        migrations.AddField(
            model_name="momentviews",
            name="moment_viewed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moment_viewed",
                to="backend.Moment",
            ),
        ),
        migrations.AddField(
            model_name="momentviews",
            name="moment_viewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moment_viewer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="momentviews",
            index=models.Index(
                fields=["moment_viewed", "timestamp"],
                name="backend_mom_moment__18a6ed_idx",
            ),
        ),
        migrations.AddField(
            model_name="momentshares",
            name="moment_shared",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moment_shared",
                to="backend.Moment",
            ),
        ),
        migrations.AddField(
            model_name="momentshares",
            name="moment_sharer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moment_sharer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="momentscores",
            name="moment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moment",
                to="backend.Moment",
            ),
        ),
        migrations.AddIndex(
            model_name="momentshares",
            index=models.Index(
                fields=["moment_shared", "timestamp"],
                name="backend_mom_moment__b8be5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="momentscores",
            index=models.Index(
                fields=["moment", "timestamp"], name="backend_mom_moment__5b675d_idx"
            ),
        ),
    ]
