# Generated by Django 3.0.7 on 2022-02-09 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('backend', '0103_auto_20220208_0123'),
        ('backend', '0105_auto_20220209_2243'),
    ]

    operations = [
    ]
