# Generated by Django 3.0.7 on 2022-02-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('backend', '0105_auto_20220210_1911'),
        ('backend', '0106_merge_20220209_2328'),
    ]

    operations = [
    ]
