# Generated by Django 3.0.7 on 2022-02-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('backend', '0103_auto_20220208_0123'),
        ('backend', '0107_merge_20220211_0436'),
    ]

    operations = [
    ]
