# Generated by Django 3.0.7 on 2022-02-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0107_auto_20220210_2346'),
        ('backend', '0107_merge_20220211_0436'),
    ]

    operations = [
    ]
