# Generated by Django 3.2.11 on 2022-02-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0104_momentcategoryeditcount'),
        ('backend', '0108_merge_20220214_0524'),
    ]

    operations = [
    ]
