# Generated by Django 3.0.7 on 2022-02-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0108_merge_20220211_2321'),
        ('backend', '0109_merge_20220214_0954'),
    ]

    operations = [
    ]
