# Generated by Django 3.2.11 on 2022-02-16 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0110_merge_20220216_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentmomentwidget',
            name='moment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taggusermeta',
            name='timestamp_dm_view_stage',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 14, 26, 50, 796065, tzinfo=utc)),
        ),
    ]
