# Generated by Django 3.0.7 on 2022-02-18 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0111_auto_20220215_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagguser',
            name='dob',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='taggusermeta',
            name='timestamp_dm_view_stage',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 14, 26, 27, 606227, tzinfo=utc)),
        ),
    ]
