# Generated by Django 3.2.11 on 2022-02-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0111_auto_20220216_1426'),
        ('backend', '0112_auto_20220218_1426'),
    ]

    operations = [
    ]
