# Generated by Django 3.0.7 on 2022-02-28 17:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0113_merge_20220224_2135'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='RewardCalculation',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('count', models.IntegerField(default=0)),
        #         ('taggId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Widget')),
        #         ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
    ]
