# Generated by Django 3.0.7 on 2022-03-02 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0114_auto_20220228_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagguser',
            name='profile_visit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taggusermeta',
            name='timestamp_dm_view_stage',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 19, 22, 31, 555396, tzinfo=utc)),
        ),
    ]
