# Generated by Django 3.2.11 on 2022-03-01 13:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0115_alter_taggusermeta_timestamp_dm_view_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagguser',
            name='thumbnail_enable',
            field=models.CharField(blank=True, choices=[('BLOCKED', 'Blocked'), ('UNBLOCKED', 'Unblocked')], default='BLOCKED', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='custom_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='widget',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='widget',
            name='status',
            field=models.CharField(choices=[('lock', 'Lock'), ('unlock', 'Unlock')], default='lock', max_length=255),
        ),
        migrations.AddField(
            model_name='widget',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taggusermeta',
            name='timestamp_dm_view_stage',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 13, 19, 29, 786909, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='RewardCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('taggId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.widget')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
