# Generated by Django 3.2.11 on 2022-03-01 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0116_auto_20220301_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggusermeta',
            name='timestamp_dm_view_stage',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 13, 23, 7, 402072, tzinfo=utc)),
        ),
    ]
