# Generated by Django 3.2.11 on 2022-03-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0115_auto_20220302_1922'),
        ('backend', '0117_alter_taggusermeta_timestamp_dm_view_stage'),
    ]

    operations = [
    ]
