# Generated by Django 3.2.11 on 2022-03-03 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0117_alter_taggusermeta_timestamp_dm_view_stage'),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name='RewardCalculation',
        #     new_name='RewardCalculation',
        # ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DFT', 'Default'), ('FRD_REQ', 'Friend Request'), ('FRD_ACPT', 'Friend Acceptance'), ('CMT', 'Comment'), ('LKT', 'Link Taggs'), ('MOM_3+', 'Moment 3P'), ('MOM_FRIEND', 'Moment Friend'), ('INVT_ONBRD', 'Invitee Onboarded'), ('MOM_TAG', 'Moment Tag'), ('SYSTEM_MSG', 'System Msg'), ('P_VIEW', 'Profile View'), ('VIEW_TAGG', 'View Tagg')], default='DFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='taggusermeta',
            name='timestamp_dm_view_stage',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 8, 31, 24, 565940, tzinfo=utc)),
        ),
    ]
