# Generated by Django 3.0.7 on 2022-03-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0117_alter_taggusermeta_timestamp_dm_view_stage'),
        ('backend', '0115_auto_20220302_1922'),
    ]

    operations = [
    ]
