# Generated by Django 3.2.11 on 2022-03-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0115_auto_20220302_1922'),
        ('backend', '0118_auto_20220303_0831'),
    ]

    operations = [
    ]
