# Generated by Django 3.2.11 on 2022-03-07 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0118_merge_20220308_0158'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='gameprofile',
        #     name='eligible_for_unlock_tagg_bg',
        #     field=models.BooleanField(default=False),
        # ),
    ]
