# Generated by Django 3.0.7 on 2022-03-04 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0118_merge_20220304_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggusermeta',
            name='timestamp_dm_view_stage',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 13, 13, 37, 760532, tzinfo=utc)),
        ),
    ]
