# Generated by Django 3.0.7 on 2022-03-08 10:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0119_auto_20220304_1313'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='taggusermeta',
        #     name='timestamp_dm_view_stage',
        #     field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 16, 23, 14, 927245, tzinfo=utc)),
        # ),
        migrations.CreateModel(
            name='DailyMoment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Moment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
