# Generated by Django 3.2.11 on 2022-03-07 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0120_auto_20220307_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='slug',
            field=models.SlugField(default='hello-world', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taggusermeta',
            name='timestamp_dm_view_stage',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 6, 26, 20, 443219, tzinfo=utc)),
        ),
    ]
