# Generated by Django 3.2.11 on 2022-03-07 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0121_auto_20220307_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggusermeta',
            name='timestamp_dm_view_stage',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 6, 29, 58, 921055, tzinfo=utc)),
        ),
        # migrations.DeleteModel(
        #     name='RewardCalculation',
        # ),
    ]
