# Generated by Django 3.2.11 on 2022-03-09 08:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0123_merge_0119_auto_20220308_0200_0122_auto_20220307_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggBackgroundImageUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagg_bg_image_unlocked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
