# Generated by Django 3.2.11 on 2022-03-09 09:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0123_merge_0119_auto_20220308_0200_0122_auto_20220307_0630'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='userfeature',
        #     name='eligible_for_unlock_tagg_bg',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AlterField(
            model_name='taggusermeta',
            name='timestamp_dm_view_stage',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 9, 19, 21, 33520, tzinfo=utc)),
        ),
    ]
