# Generated by Django 3.2.11 on 2022-03-09 11:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0124_auto_20220309_0919'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='gameprofile',
        #     name='eligible_for_unlock_tagg_bg',
        # ),
        migrations.AlterField(
            model_name='taggusermeta',
            name='timestamp_dm_view_stage',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 11, 43, 21, 305889, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='TaggTitleFontColorUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagg_title_font_color_unlocked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
