# Generated by Django 3.2.11 on 2022-03-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0119_auto_20220308_0200'),
        ('backend', '0122_auto_20220307_0630'),
    ]

    operations = [
    ]
