# Generated by Django 3.2.11 on 2022-03-10 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0120_auto_20220308_1623'),
        ('backend', '0124_auto_20220309_1425'),
        ('backend', '0125_auto_20220309_1143'),
        ('backend', '0143_merge_20220309_0824'),
    ]

    operations = [
    ]
