# Generated by Django 3.2.11 on 2022-03-16 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0146_auto_20220312_0324"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameprofile",
            name="newRewardsReceived",
            field=models.CharField(default="[]", max_length=1024),
        ),
    ]
