# Generated by Django 3.2.11 on 2022-03-16 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0147_auto_20220316_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcalculation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taggusermeta',
            name='timestamp_dm_view_stage',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('VIDEO_LINK', 'Video Link'), ('APPLICATION_LINK', 'Application Link'), ('GENERIC_LINK', 'Generic Link'), ('SOCIAL_MEDIA', 'Social Media')], max_length=64),
        ),
        migrations.CreateModel(
            name='TaggThumbnailImageUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagg_thumb_image_unlocked', models.BooleanField(default=False)),
                ('is_award_shown', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
