# Generated by Django 3.2.11 on 2022-03-17 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0147_auto_20220316_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileColorGradient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color1', models.CharField(max_length=7)),
                ('background_color2', models.CharField(max_length=7)),
                ('tab_color1', models.CharField(max_length=7)),
                ('tab_color2', models.CharField(max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
