# Generated by Django 3.0.7 on 2022-03-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0148_auto_20220316_0843'),
        ('backend', '0148_auto_20220317_1339'),
    ]

    operations = [
    ]
