# Generated by Django 3.2.11 on 2022-03-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0148_auto_20220316_0843'),
        ('backend', '0148_auto_20220317_1339'),
    ]

    operations = [
    ]
