# Generated by Django 3.0.7 on 2022-03-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0149_merge_20220323_1007'),
    ]

    operations = [

        migrations.AddField(
            model_name='taggusermeta',
            name='contact_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taggusermeta',
            name='location_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taggusermeta',
            name='notification_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taggusermeta',
            name='permission_completed',
            field=models.BooleanField(default=False),
        ),
    ]
