# Generated by Django 3.2.11 on 2022-03-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0149_merge_0148_auto_20220316_0843_0148_auto_20220317_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='primary_color',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='skin',
            name='secondary_color',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='ProfileColorGradient',
        ),
    ]
