# Generated by Django 3.2.11 on 2022-03-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0150_auto_20220322_1724'),
        ('backend', '0150_auto_20220323_1007'),
    ]

    operations = [
    ]
