# Generated by Django 3.2.11 on 2022-03-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0151_merge_0150_auto_20220322_1724_0150_auto_20220323_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediawidget',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
