# Generated by Django 3.0.7 on 2022-04-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0152_auto_20220328_1709'),
        ('backend', '0152_auto_20220328_1836'),
    ]

    operations = [
    ]
