# Generated by Django 3.0.7 on 2022-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0153_merge_20220404_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggusermeta',
            name='background_gradient_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taggusermeta',
            name='tab_permission',
            field=models.BooleanField(default=False),
        ),
    ]
