# Generated by Django 3.0.7 on 2022-03-30 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0153_merge_20220330_1621'),
    ]

    operations = [

        migrations.AddField(
            model_name='dailymoment',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailymoment_owner_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
