# Generated by Django 3.2.11 on 2022-04-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0154_auto_20220330_1622'),
        ('backend', '0154_auto_20220404_2240'),
    ]

    operations = [
    ]
