# Generated by Django 3.2.11 on 2022-04-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0155_merge_0154_auto_20220330_1622_0154_auto_20220404_2240'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='gameprofile',
        #     name='eligible_for_unlock_tagg_bg',
        # ),
        migrations.RemoveField(
            model_name='taggusermeta',
            name='background_gradient_permission',
        ),
        migrations.RemoveField(
            model_name='taggusermeta',
            name='tab_permission',
        ),
        migrations.AddField(
            model_name='logincount',
            name='last_login',
            field=models.DateField(default=None, null=True),
        ),
    ]
